import {templates, sources as originalSources, topics} from './data.js';
import {escapeHTML as e, retrieve, makeBrief, addExpertToBrief, generateDraft, reviseDraft, markdown, words, checks} from './engine.js';
const APP_KEY='prism-editorial-v1', AUTH_KEY='prism-session';
const app=document.querySelector('#app'), modal=document.querySelector('#modal');
let state, tab='overview', activeTopic='outbound', busy=false, dirty=false, timer;
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6 M8 13h8 M8 17h6',book:'M4 3h13a3 3 0 0 1 3 3v15H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3 M3 17h17 M7 7h9 M7 11h7',layers:'M12 3 2 8l10 5 10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',check:'m5 12 4 4L19 6',plus:'M12 5v14 M5 12h14',clock:'M12 8v4l3 3 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',key:'M8 15a5 5 0 1 1 4-8l9 0v4h-3v3h-4l-2-2',logout:'M9 5H4v14h5 M12 12h9 m-4-4 4 4-4 4',download:'M12 3v12 m-4-4 4 4 4-4 M4 16v5h16v-5',arrow:'m9 5 7 7-7 7',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;
const logo=()=>'<div class="logo"><img src="favicon.svg" alt="">Prism <span>EDITORIAL</span></div>';
const stamp=()=>new Date().toISOString();
const displayDate=s=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const notify=(message)=>{const box=document.querySelector('#toast');box.textContent=message;box.style.display='block';clearTimeout(timer);timer=setTimeout(()=>box.style.display='none',3500);};
function persist(){try{localStorage.setItem(APP_KEY,JSON.stringify(state));return true;}catch{notify('Browser storage is full or unavailable. Export your work before leaving.');return false;}}
function history(record,label){record.updated=stamp();record.events.unshift({label,at:stamp()});}
function makeRecord(topic,extra={}){return {id:crypto.randomUUID(),topicId:topic.id,title:topic.title,type:topic.type,keyword:topic.keyword,angle:topic.angle,audience:'B2B growth and revenue leaders',target:1000,status:'Brief review',created:stamp(),updated:stamp(),questions:structuredClone(topic.questions),answers:[],brief:'',draft:'',sources:[],versions:[],events:[],reviewNote:'',...extra};}
function seed(){const result={version:1,sources:structuredClone(originalSources),articles:[]};
 topics.slice(0,3).forEach((topic,i)=>{const r=makeRecord(topic);const b=makeBrief(r,result.sources);r.brief=b.text;r.sources=b.sources;r.answers=structuredClone(topic.answers);addExpertToBrief(r);r.status='Ready to draft';r.draft=generateDraft(r);r.versions=[{number:1,text:r.draft,at:stamp(),note:'Prepared demonstration article'}];r.status=i===0?'Approved':i===1?'Article review':'Expert input';if(i===2){r.answers=[];r.brief=b.text;r.draft='';r.versions=[];}r.events=[{label:i===0?'Article approved by demo editor':i===1?'Draft assembled from approved brief':'Expert questions prepared',at:stamp()},{label:'Brief assembled from context library',at:stamp()}];result.articles.push(r);});return result;}
try{state=JSON.parse(localStorage.getItem(APP_KEY));if(!state||state.version!==1||!Array.isArray(state.articles)||!Array.isArray(state.sources))state=seed();}catch{state=seed();}persist();
const authenticated=()=>{try{return sessionStorage.getItem(AUTH_KEY)==='demo';}catch{return false;}};
function badge(status){const cls=status==='Approved'?'teal':status.includes('review')?'amber':status==='Ready to draft'?'teal':'purple';return `<span class="tag ${cls}">${e(status)}</span>`;}
function navLink(route,label,ic){return `<a href="#/${route}" class="${location.hash.startsWith('#/'+route)?'active':''}">${icon(ic)}${label}</a>`;}
function shell(content,title='Overview') {app.innerHTML=`<div class="shell"><aside class="sidebar">${logo()}<a class="btn primary full new-btn" href="#/new">${icon('plus')}New article</a><div class="nav-caption">Workspace</div><nav class="nav" aria-label="Main navigation">${navLink('overview','Overview','grid')}${navLink('articles','Article library','file')}${navLink('knowledge','Knowledge base','book')}${navLink('templates','Templates','layers')}</nav><div class="side-bottom"><div class="demo-card"><strong><span class="demo-dot"></span>Demonstration workspace</strong>Prepared content. Real workflow.<br>No external AI connection.</div><div class="row"><div class="avatar">DE</div><div><b style="color:#eee">Demo editor</b><br>Single-user workspace</div><button class="linkbtn" data-action="logout" aria-label="Sign out" style="color:#baafd0;margin-left:auto;width:20px">${icon('logout')}</button></div></div></aside><div class="workspace"><header class="topbar"><div class="crumb">Workspace <span style="margin:0 10px;color:#ccc">/</span> <strong style="color:var(--ink)">${e(title)}</strong></div><div class="row"><span class="tag teal">Demo mode</span><button class="linkbtn small" data-action="guide">Demo guide</button><button class="avatar" style="border:0" data-action="logout" aria-label="Sign out">DE</button></div></header><main id="main" class="content">${content}</main></div></div>`;}
function login(){app.innerHTML=`<main class="login" id="main"><section class="login-story">${logo()}<div><div class="eyebrow" style="color:#62d9cd">The content behind your content</div><h1>Turn what you know<br>into what they<br><em>want to read.</em></h1><p>A thoughtful path from company knowledge to content worth publishing.</p><div class="login-process"><div><span>01</span>Your context, connected</div><div><span>02</span>Expert knowledge, brought in</div><div><span>03</span>Human judgment, built in</div></div></div><footer>PRISM EDITORIAL / INTERACTIVE PRODUCT DEMO</footer></section><section class="login-form"><div class="login-box"><div class="login-symbol">${icon('key')}</div><h2>Welcome to your studio.</h2><p class="muted">Sign in to explore the complete editorial workflow.</p><form id="login-form"><div class="field"><label for="email">Email address</label><input id="email" type="email" autocomplete="username" placeholder="Your demo email" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" placeholder="Your demo password" required></div><div id="login-error" class="error hidden" role="alert">Use the demo credentials provided with your invitation.</div><button class="btn primary full" type="submit">Enter workspace</button></form><div class="notice" style="font-size:12px;margin-top:25px">A shared demo sign-in for presentations. All examples are fictional. Edits stay in this browser; this demo does not protect confidential data.</div><p class="small muted">From brief to expert input to approved article.<br>No AI account or API key needed.</p></div></section></main>`;}
const articleRow=r=>`<a class="article-row" href="#/article/${r.id}"><div class="file-icon">${icon('file')}</div><div class="grow"><h3>${e(r.title)}</h3><div class="meta">${r.type==='howto'?'How-to guide':'Comparison'} <span style="margin:0 7px">·</span> ${displayDate(r.updated)} <span style="margin:0 7px">·</span> ${r.sources.length} context sources</div></div>${badge(r.status)}</a>`;
function overview(){const a=state.articles;return `<div class="page-head"><div class="eyebrow" style="display:none">Workspace</div><div><h1>Good content starts here.</h1><p>Your knowledge, your experts, one connected editorial process.</p></div><a href="#/new" class="btn primary">+ Create an article</a></div><div class="stat-grid">${[[a.length,'Articles in your library','file','Across the editorial workflow'],[a.filter(r=>r.status==='Approved').length,'Ready to use','check','Reviewed and approved'],[a.filter(r=>r.status.includes('review')||r.status==='Expert input').length,'Need your attention','clock','Keep the work moving'],[state.sources.length,'Knowledge sources','book','Context behind every draft']].map(([n,label,ic,sub])=>`<div class="stat"><div class="stat-top">${label}${icon(ic)}</div><span class="num">${n.toString().padStart(2,'0')}</span><span class="small">${sub}</span></div>`).join('')}</div><div class="split"><section class="panel tight"><div class="section-head row spread"><h2>Recent articles</h2><a href="#/articles" class="linkbtn">View library</a></div>${a.slice(0,5).map(articleRow).join('')||'<div class="empty">Your first article starts with a topic.</div>'}<div style="padding:20px 24px;background:#fcfbfe;border-radius:0 0 13px 13px;font-size:13px;color:var(--muted)">Every article keeps its brief, source context, decisions and revisions together.</div></section><aside><div class="panel accent-panel"><div class="eyebrow">From an idea to a useful article</div><h2>A blank page.<br>A better starting point.</h2><p>Pick a topic. Let your knowledge library shape the brief. Bring in an expert where it matters.</p><a href="#/new" class="btn">Start a new article</a></div><div class="panel" style="margin-top:18px"><h3>The editorial path</h3>${[['Context → brief','Templates and source material'],['Expert → approval','Close gaps, then lock direction'],['Draft → refinement','Review, revise and export']].map(([x,y],i)=>`<div class="mini-step"><span class="stepnum">${i+1}</span><div><b>${x}</b>${y}</div></div>`).join('')}</div></aside></div><p class="bottom-note">Local demonstration workspace · Changes are saved in this browser. Use Export to keep a copy.</p>`;}
function library(){return `<div class="page-head"><div><h1>Article library</h1><p>Every draft, decision and finished piece, in one place.</p></div><a href="#/new" class="btn primary">+ New article</a></div><div class="searchbar"><input class="search" id="article-search" aria-label="Search articles" placeholder="Search articles by title or keyword"><select id="status-filter" aria-label="Filter by status"><option value="">All statuses</option>${['Brief review','Expert input','Ready to draft','Article review','Approved'].map(s=>`<option>${s}</option>`).join('')}</select><select id="type-filter" aria-label="Filter by type"><option value="">All types</option><option value="howto">How-to guide</option><option value="listicle">Comparison / listicle</option></select></div><div id="article-list" class="panel tight">${state.articles.map(articleRow).join('')}</div>`;}
function filterLibrary(){const query=document.querySelector('#article-search').value.toLowerCase(),status=document.querySelector('#status-filter').value,type=document.querySelector('#type-filter').value;document.querySelector('#article-list').innerHTML=state.articles.filter(r=>(r.title+' '+r.keyword).toLowerCase().includes(query)&&(!status||r.status===status)&&(!type||r.type===type)).map(articleRow).join('')||'<div class="empty">No articles match these filters.</div>';}
function newArticle(){const t=topics.find(t=>t.id===activeTopic);return `<div class="page-head"><div><h1>What are we writing?</h1><p>Choose a prepared scenario, then make the brief your own.</p></div><span class="tag purple">Step 1 of 5</span></div><div class="split"><section><div class="topic-grid" style="margin-top:0">${topics.map(topic=>`<button class="topic-card ${topic.id===activeTopic?'selected':''}" data-action="topic" data-id="${topic.id}" aria-pressed="${topic.id===activeTopic}"><span class="tag ${topic.type==='howto'?'teal':'purple'}">${topic.type==='howto'?'How-to guide':'Comparison'}</span><h3>${topic.title}</h3><p>${topic.angle}</p></button>`).join('')}</div><form id="new-form" class="panel"><h2>Set the direction</h2><div class="form-grid"><div class="field fullspan"><label for="article-title">Working title</label><input id="article-title" name="title" value="${e(t.title)}" required maxlength="180"></div><div class="field"><label for="keyword">Primary keyword</label><input id="keyword" name="keyword" value="${e(t.keyword)}" required maxlength="100"></div><div class="field"><label for="target">Target length</label><select id="target" name="target"><option value="800">800 words</option><option value="1000" selected>1,000 words</option><option value="1200">1,200 words</option></select></div><div class="field fullspan"><label for="audience">Audience</label><input id="audience" name="audience" value="B2B growth and revenue leaders" required maxlength="200"></div><div class="field fullspan"><label for="angle">Angle / reader outcome</label><textarea id="angle" name="angle" required maxlength="1500">${e(t.angle)}</textarea><small>Title and brief can be customized. The article body follows your selected prepared scenario.</small></div></div><div class="form-footer row spread wrap"><span class="small muted">${templates.find(x=>x.id===t.type).name} template</span><button class="btn primary" type="submit">Build the brief</button></div></form></section><aside class="rail" style="display:block"><div class="panel"><div class="eyebrow">Context preview</div><h3>A foundation for this topic</h3><p class="aside-note">The brief will use matching knowledge plus shared brand and editorial rules.</p>${retrieve(t.title,t.type,state.sources).slice(0,6).map(s=>`<div class="source-item"><b>${e(s.title)}</b><span>${e(s.kind)}</span></div>`).join('')}<a href="#/knowledge" class="linkbtn">Explore the knowledge base</a></div><div class="notice">Demo mode assembles prepared content. It does not perform live research or generate arbitrary topics.</div></aside></div>`;}
function knowledge(){return `<div class="page-head"><div><h1>The knowledge behind the words.</h1><p>Company rules, expert experience and buyer context that shape every brief.</p></div><button class="btn primary" data-action="add-source">+ Add source</button></div><div class="notice teal">Edit a source, then create a new brief to see the updated context. Existing articles keep a snapshot of the sources used.</div><div class="searchbar"><input id="source-search" class="search" aria-label="Search knowledge" placeholder="Search knowledge by title, content or category"></div><div class="knowledge-grid" id="knowledge-grid">${state.sources.map(sourceCard).join('')}</div>`;}
function sourceCard(s){return `<article class="panel knowledge-card"><div class="row spread"><span class="tag ${s.kind==='Expert knowledge'?'teal':'purple'}">${e(s.kind)}</span>${icon('file')}</div><h3>${e(s.title)}</h3><p>${e(s.text.slice(0,145))}${s.text.length>145?'…':''}</p><div class="kbowner"><small>${e(s.owner)}</small><button class="linkbtn" data-action="edit-source" data-id="${s.id}">View & edit</button></div></article>`;}
function templatePage(){return `<div class="page-head"><div><h1>Structure with a purpose.</h1><p>Different reading needs call for different editorial frameworks.</p></div></div><div class="topic-grid">${templates.map(t=>`<section class="panel"><div class="row spread"><span class="tag teal">${t.intent}</span><span class="template-num">${t.icon}</span></div><h2 style="margin:22px 0 6px">${t.name}</h2><p class="muted">${t.label}</p><h3>Article structure</h3>${t.sections.map((s,i)=>`<div class="mini-step"><span class="stepnum">${i+1}</span><div>${e(s)}</div></div>`).join('')}<h3 style="margin-top:25px">Editorial requirements</h3><ul class="small muted">${t.rules.map(r=>'<li style="margin:10px 0">'+e(r)+'</li>').join('')}</ul><button class="btn primary" data-action="use-template" data-id="${t.id}">Use this template</button></section>`).join('')}</div>`;}
function currentRecord(){return state.articles.find(r=>r.id===location.hash.split('/')[2]);}
function workflow(r){const idx=['Brief review','Expert input','Ready to draft','Article review','Approved'].indexOf(r.status);return `<div class="stepper" aria-label="Workflow progress">${['Brief','Expert input','Brief approval','Article','Final approval'].map((s,i)=>`<div class="flow-step ${i<idx?'done':i===idx?'current':''}" ${i===idx?'aria-current="step"':''}><span class="circle">${i<idx?'✓':i+1}</span>${s}</div>`).join('')}</div>`;}
function rail(r){const quality=r.draft?checks(r):[];return `<aside class="rail"><div class="panel"><div class="row spread"><h3>Context used</h3><span class="tag teal">${r.sources.length}</span></div><p class="aside-note">A saved snapshot of the material behind this brief.</p>${r.sources.map(s=>`<div class="source-item"><button class="linkbtn" style="color:var(--ink)" data-action="view-snapshot" data-id="${s.id}">${e(s.title)}</button><br><span>${e(s.kind)}</span></div>`).join('')}</div><div class="panel"><h3>${r.draft?'Editorial checks':'Human checkpoints'}</h3>${r.draft?quality.map(c=>`<div class="check-item"><span class="${c.ok?'pass':'warn'}">${c.ok?'✓':'○'}</span>${c.label}</div>`).join('')+'<p class="aside-note" style="margin-top:16px;margin-bottom:0">Rule-based checks only. The editor verifies facts, tone and fit with the brief.</p>':[['Direction & outline','Editor'],['Knowledge gaps','Knowledge keeper'],['Completed brief','Editor'],['Final article','Editor']].map(([s,owner])=>`<div class="mini-step"><span class="stepnum">✓</span><div><b>${s}</b>${owner}</div></div>`).join('')}</div></aside>`;}
function article(r){if(!r)return '<div class="empty"><h1>Article not found</h1><a href="#/articles">Return to the library</a></div>';let body='';
 if(tab==='overview'){
 if(r.status==='Brief review')body=`<div class="action-banner"><div><strong>Your brief is ready for review.</strong>Check the direction before preparing expert questions.</div><button class="btn primary" data-action="request-expert">Confirm direction</button></div><div class="row spread" style="padding:20px 24px 0"><span class="tag purple">Brief v1</span><button class="linkbtn" data-action="edit-brief">Edit brief</button></div><div class="document">${markdown(r.brief)}</div>`;
 else if(r.status==='Expert input')body=`<div class="action-banner"><div><strong>A little first-hand knowledge goes a long way.</strong>Two gaps are ready for a knowledge keeper to resolve.</div><span class="tag purple">Expert checkpoint</span></div><div style="padding:27px"><div class="row" style="margin-bottom:22px"><div class="avatar">JL</div><div><b>Jordan Lee</b><div class="small muted">Knowledge keeper · simulated role</div></div></div><p class="small muted">Questions stay in this workspace. You can answer as the expert or load the prepared example.</p><form id="expert-form">${r.questions.map((q,i)=>`<div class="field" style="margin:23px 0"><label for="answer-${i}">${i+1}. ${e(q)}</label><textarea id="answer-${i}" name="answer${i}" minlength="30" maxlength="3000" required placeholder="Add a specific example, explain what you do and why…">${e(r.answers[i]||'')}</textarea><small>At least 30 characters. Specificity is reviewed by the editor.</small></div>`).join('')}<div class="row spread wrap form-footer"><button type="button" class="btn" data-action="sample-expert">Use example answers</button><button class="btn primary" type="submit">Submit expert input</button></div></form></div>`;
 else if(r.status==='Ready to draft')body=`<div class="action-banner teal"><div><strong>Expert input is now part of the brief.</strong>Approve the completed brief to assemble the article.</div></div><div style="padding:22px 24px;border-bottom:1px solid var(--line)"><label class="small row" style="align-items:flex-start"><input type="checkbox" id="brief-approval" style="margin-top:5px">I reviewed the brief, source context and expert input.</label><div class="row wrap" style="margin-top:17px"><button class="btn primary" id="generate-btn" data-action="generate" disabled>Approve brief & create article</button><button class="btn" data-action="return-expert">Return to expert</button><button class="linkbtn" data-action="edit-brief">Edit brief</button></div></div><div class="document">${markdown(r.brief)}</div>`;
 else body=`<div class="action-banner ${r.status==='Approved'?'teal':''}"><div><strong>${r.status==='Approved'?'Approved and ready to use.':'Your article is ready for the editor.'}</strong>${r.status==='Approved'?'Export the article, or create a new revision.':'Review the content, refine the wording and confirm the final version.'}</div>${r.status==='Approved'?'<button class="btn" data-action="edit-article">Create revision</button>':'<button class="btn primary" data-action="approve-article">Review & approve</button>'}</div><div class="metric-band"><span><strong>${words(r.draft)}</strong> words</span><span><strong>v${r.versions.length}</strong> current version</span><span>${checks(r).filter(x=>x.ok).length}/${checks(r).length} automated checks</span><span style="margin-left:auto"><button class="linkbtn" data-action="edit-article">Edit article</button></span></div><div class="document">${markdown(r.draft)}</div>`;
 }else if(tab==='brief')body=`<div class="row spread" style="padding:22px 24px 0"><span class="tag purple">${r.answers.length?'Expert-enriched brief':'Working brief'}</span>${!r.draft?'<button class="linkbtn" data-action="edit-brief">Edit brief</button>':'<span class="small muted">Approved snapshot</span>'}</div><div class="document">${markdown(r.brief)}</div>`;
 else if(tab==='versions')body=`<div style="padding:26px"><h2>Version history</h2><p class="small muted">Open or restore a saved version. Restoring creates a new version for review.</p>${r.versions.map(v=>`<div class="version row spread wrap"><div><b>Version ${v.number}</b><div class="small muted">${e(v.note)} · ${displayDate(v.at)} · ${words(v.text)} words</div></div><div class="row"><button class="btn sm" data-action="view-version" data-id="${v.number}">View</button><button class="btn sm" data-action="restore-version" data-id="${v.number}">Restore</button></div></div>`).join('')||'<div class="empty">Your article versions will appear here after drafting.</div>'}</div>`;
 else body=`<div style="padding:28px"><h2>Activity & decisions</h2><p class="small muted">A local record of how this article took shape.</p><div class="timeline" style="margin-top:25px">${r.events.map(ev=>`<div class="event">${e(ev.label)}<small>${new Date(ev.at).toLocaleString('en-US')}</small></div>`).join('')}</div></div>`;
 return `<div class="page-head"><div><div class="row" style="margin-bottom:12px"><a class="linkbtn" href="#/articles">Article library</a><span style="color:#ccc">/</span>${badge(r.status)}</div><h1 style="font-size:26px;max-width:800px">${e(r.title)}</h1><p>${r.type==='howto'?'How-to guide':'Comparison / listicle'} · ${e(r.keyword)}</p></div>${r.draft?'<button class="btn" data-action="export">'+icon('download')+'Export</button>':''}</div>${workflow(r)}<div class="split"><section class="panel tight"><div class="tabs" role="tablist" aria-label="Article views">${[['overview',r.draft?'Article':'Workflow'],['brief','Brief'],['versions','Versions'],['activity','Activity']].map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}" data-action="tab" data-id="${id}">${label}${id==='versions'?' ('+r.versions.length+')':''}</button>`).join('')}</div>${body}</section>${rail(r)}</div>`;
}
function render(){if(!authenticated()){login();return;}const route=location.hash.split('/')[1]||'overview';if(route!=='article')tab='overview';shell(route==='overview'?overview():route==='articles'?library():route==='new'?newArticle():route==='knowledge'?knowledge():route==='templates'?templatePage():route==='article'?article(currentRecord()):overview(),{overview:'Overview',articles:'Article library',new:'New article',knowledge:'Knowledge base',templates:'Templates',article:'Article workspace'}[route]||'Overview');}
function showModal(html){modal.innerHTML=html;modal.showModal();}
function closeModal(){modal.close();dirty=false;}
function sourceModal(source,newItem=false){showModal(`<form id="source-form" data-id="${source.id||''}"><div class="row spread"><h2>${newItem?'Add knowledge source':'Knowledge source'}</h2><button type="button" class="linkbtn" data-action="close-modal">Close</button></div><div class="form-grid"><div class="field fullspan"><label for="source-title">Source title</label><input id="source-title" name="title" required maxlength="150" value="${e(source.title||'')}"></div><div class="field"><label for="source-kind">Category</label><select id="source-kind" name="kind">${['Brand','Rules','SEO','Audience','Expert knowledge','Customer voice','Market context','Examples','Case library','Internal links'].map(k=>`<option ${source.kind===k?'selected':''}>${k}</option>`).join('')}</select></div><div class="field"><label for="source-owner">Owner</label><input id="source-owner" name="owner" required maxlength="120" value="${e(source.owner||'Demo editor')}"></div><div class="field fullspan"><label for="source-tags">Topic tags</label><input id="source-tags" name="tags" value="${e((source.tags||['all']).join(', '))}" required maxlength="200"><small>Comma-separated keywords. Use “all” to apply to every article.</small></div><div class="field fullspan"><label for="source-text">Knowledge / rules</label><textarea id="source-text" name="text" required maxlength="15000">${e(source.text||'')}</textarea></div></div><div class="row spread form-footer"><span class="small muted">Saved in this browser</span><button class="btn primary" type="submit">Save source</button></div></form>`);}
function saveVersion(r,note,text){r.draft=text;r.versions.push({number:r.versions.length+1,text,at:stamp(),note});r.status='Article review';history(r,note);persist();}
function editArticle(r){showModal(`<div class="row spread"><h2>Edit article</h2><button class="linkbtn" data-action="close-modal">Close</button></div><div class="row wrap" style="margin-bottom:15px"><button class="btn sm" data-action="rewrite" data-id="intro">Tighten introduction</button><button class="btn sm" data-action="rewrite" data-id="checklist">Add practical checklist</button></div><p class="small muted">Edit Markdown directly, or apply a prepared revision. Saving creates a new version and requires fresh approval.</p><form id="article-edit-form"><textarea class="editor" id="draft-edit" aria-label="Article text" required maxlength="100000">${e(r.draft)}</textarea><div class="field" style="margin-top:16px"><label for="revision-note">Revision note</label><input id="revision-note" name="note" value="Editorial revision" required maxlength="300"></div><div class="row spread form-footer"><span class="small muted">Version ${r.versions.length+1}</span><button class="btn primary" type="submit">Save new version</button></div></form>`);}
function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportArticle(r,format){const filename=r.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(format==='md')download(filename+'.md',r.draft,'text/markdown');else download(filename+'.html',`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(r.title)}</title><style>body{max-width:800px;margin:50px auto;padding:25px;font:18px/1.75 Georgia,serif;color:#252033}h1,h2,h3{line-height:1.3}table{border-collapse:collapse;font:14px/1.5 sans-serif}td{border:1px solid #ddd;padding:10px}.table-scroll{overflow:auto}</style></head><body>${markdown(r.draft)}</body></html>`,'text/html');notify('Article exported.');}
async function buildWithProgress(message,task){busy=true;shell(`<div class="panel busy"><div class="spinner"></div><h2>${message}</h2><p class="muted">Matching source context and assembling the prepared scenario.</p><span class="tag purple">Demo assembly · no live AI request</span></div>`,'Preparing content');await new Promise(resolve=>setTimeout(resolve,1100));try{task();persist();}catch(err){notify(err.message);}finally{busy=false;render();window.scrollTo(0,0);}}
document.addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.target,r=currentRecord();
 if(form.id==='login-form'){if(document.querySelector('#email').value.trim().toLowerCase()==='sales@prism.demo'&&document.querySelector('#password').value==='PrismDemo!26'){try{sessionStorage.setItem(AUTH_KEY,'demo');location.hash='#/overview';render();window.scrollTo(0,0);}catch{document.querySelector('#login-error').textContent='Enable browser storage to use this workspace.';document.querySelector('#login-error').classList.remove('hidden');}}else document.querySelector('#login-error').classList.remove('hidden');}
 if(form.id==='new-form'){const d=Object.fromEntries(new FormData(form));const record=makeRecord(topics.find(t=>t.id===activeTopic),{...d,target:Number(d.target)});await buildWithProgress('Building your brief',()=>{const result=makeBrief(record,state.sources);record.brief=result.text;record.sources=result.sources;history(record,'Brief assembled from '+record.sources.length+' context sources');state.articles.unshift(record);tab='overview';location.hash='#/article/'+record.id;});}
 if(form.id==='expert-form'){const d=new FormData(form);const answers=r.questions.map((q,i)=>String(d.get('answer'+i)).trim());if(answers.some(a=>a.length<30)){notify('Add a specific response of at least 30 characters to each question.');return;}r.answers=answers;addExpertToBrief(r);r.status='Ready to draft';history(r,'Expert input captured and added to the brief');persist();render();window.scrollTo(0,0);notify('The completed brief is ready for approval.');}
 if(form.id==='source-form'){const data=Object.fromEntries(new FormData(form));data.tags=data.tags.toLowerCase().split(',').map(s=>s.trim()).filter(Boolean);if(!data.tags.length)data.tags=['all'];const item=state.sources.find(s=>s.id===form.dataset.id);if(item)Object.assign(item,data);else state.sources.push({...data,id:crypto.randomUUID()});persist();closeModal();render();notify('Knowledge source saved. New briefs will use this context.');}
 if(form.id==='article-edit-form'){const text=document.querySelector('#draft-edit').value.trim();if(!text){notify('Article cannot be empty.');return;}saveVersion(r,form.elements.note.value,text);closeModal();render();notify('Revision saved. Final approval is required again.');}
 if(form.id==='brief-edit-form'){r.brief=document.querySelector('#brief-edit').value;history(r,'Brief edited by demo editor');persist();closeModal();render();notify('Brief saved.');}
 if(form.id==='approve-form'){r.status='Approved';r.reviewNote=form.elements.note.value;history(r,'Article v'+r.versions.length+' approved by demo editor'+(r.reviewNote?' · '+r.reviewNote:''));persist();closeModal();render();notify('Article approved. Ready to export.');}
});
document.addEventListener('click',async ev=>{const button=ev.target.closest('[data-action]');if(!button||busy)return;const action=button.dataset.action,id=button.dataset.id,r=currentRecord();
 if(action==='logout'){sessionStorage.removeItem(AUTH_KEY);login();return;}
 if(action==='topic'){activeTopic=id;render();}
 if(action==='use-template'){activeTopic=topics.find(t=>t.type===id).id;location.hash='#/new';}
 if(action==='tab'){tab=id;render();}
 if(action==='close-modal'){if(dirty){showModal('<h2>Keep your changes?</h2><p>You have unsaved changes. Close without saving?</p><div class="row"><button class="btn" data-action="discard-modal">Discard changes</button><button class="btn primary" data-action="cancel-discard">Keep editing</button></div>');}else closeModal();}
 if(action==='discard-modal')closeModal();
 if(action==='cancel-discard'){notify('Reopen the editor to continue.');closeModal();}
 if(action==='add-source')sourceModal({},true);
 if(action==='edit-source')sourceModal(state.sources.find(s=>s.id===id));
 if(action==='view-snapshot'){const s=r.sources.find(s=>s.id===id);showModal(`<div class="row spread"><span class="tag teal">Source snapshot</span><button class="linkbtn" data-action="close-modal">Close</button></div><h2 style="margin-top:20px">${e(s.title)}</h2><p>${e(s.text)}</p><p class="small muted">${e(s.owner)} · ${e(s.kind)}</p><div class="notice">This is the source version used when the brief was created.</div>`);}
 if(action==='request-expert'&&r.status==='Brief review'){r.status='Expert input';history(r,'Direction approved; expert question packet prepared');persist();render();}
 if(action==='sample-expert'){topics.find(t=>t.id===r.topicId).answers.forEach((a,i)=>document.querySelector('#answer-'+i).value=a);notify('Example answers loaded. Review and submit them.');}
 if(action==='return-expert'&&r.status==='Ready to draft'){r.status='Expert input';history(r,'Completed brief returned for expert clarification');persist();render();}
 if(action==='generate'&&r.status==='Ready to draft'&&document.querySelector('#brief-approval').checked){await buildWithProgress('Assembling your article',()=>{history(r,'Completed brief approved by demo editor');saveVersion(r,'Draft assembled from approved brief',generateDraft(r));});}
 if(action==='edit-brief'&&!r.draft){showModal(`<div class="row spread"><h2>Edit brief</h2><button class="linkbtn" data-action="close-modal">Close</button></div><form id="brief-edit-form"><textarea id="brief-edit" class="editor" aria-label="Brief text" required maxlength="50000">${e(r.brief)}</textarea><div class="row spread form-footer"><span class="small muted">Changes stay with this article</span><button class="btn primary" type="submit">Save brief</button></div></form>`);}
 if(action==='edit-article'&&r.draft)editArticle(r);
 if(action==='rewrite'){const field=document.querySelector('#draft-edit');field.value=reviseDraft(field.value,id);document.querySelector('#revision-note').value=id==='intro'?'Tightened introduction':'Added practical checklist';notify('Prepared revision applied. Save to keep it.');}
 if(action==='approve-article'){const c=checks(r);showModal(`<h2>Approve the final article</h2><p class="muted">${c.filter(x=>x.ok).length} of ${c.length} automated checks pass. Review any open item and make the final editorial decision.</p>${c.filter(x=>!x.ok).map(x=>`<div class="notice">Needs review: ${e(x.label)}</div>`).join('')}<form id="approve-form"><label class="row small" style="align-items:flex-start;margin-bottom:20px"><input type="checkbox" required style="margin-top:5px">I have reviewed accuracy, source context, expert input and editorial quality.</label><div class="field"><label for="approval-note">Approval note${c.some(x=>!x.ok)?' (explain open checks)':' (optional)'}</label><textarea id="approval-note" name="note" ${c.some(x=>!x.ok)?'required':''} maxlength="2000" style="min-height:90px!important"></textarea></div><div class="row form-footer"><button class="btn" type="button" data-action="close-modal">Keep reviewing</button><button class="btn teal" type="submit">Approve article</button></div></form>`);}
 if(action==='view-version'){const v=r.versions.find(v=>v.number===Number(id));showModal(`<div class="row spread"><h2>Version ${v.number}</h2><button class="linkbtn" data-action="close-modal">Close</button></div><div class="document" style="padding:0">${markdown(v.text)}</div>`);}
 if(action==='restore-version'){const v=r.versions.find(v=>v.number===Number(id));saveVersion(r,'Restored version '+id,v.text);render();notify('Restored as a new version for review.');}
 if(action==='export'){showModal(`<h2>Export article</h2><p class="muted">Download the current saved version of this article.</p><div class="row"><button class="btn primary" data-action="export-md">Markdown (.md)</button><button class="btn" data-action="export-html">Formatted HTML</button><button class="linkbtn" data-action="close-modal">Close</button></div>`);}
 if(action==='export-md'||action==='export-html'){exportArticle(r,action==='export-md'?'md':'html');closeModal();}
 if(action==='guide'){showModal(`<div class="row spread"><h2>Your five-minute walkthrough</h2><button class="linkbtn" data-action="close-modal">Close</button></div><ol class="small" style="line-height:2"><li>Open the knowledge base and review company rules.</li><li>Create an article using a prepared topic.</li><li>Review the brief and confirm the direction.</li><li>Answer as the expert, or load the example answers.</li><li>Approve the completed brief and create the article.</li><li>Edit a paragraph, save a new version and approve.</li><li>Export the article and find it in the library.</li></ol><div class="notice">Demo scope: prepared content, fictional knowledge, simulated roles and browser-local history. There is no live AI, external research, shared database or real permission system.</div><button class="btn" data-action="reset-confirm">Reset demo workspace</button>`);}
 if(action==='reset-confirm'){showModal('<h2>Reset this browser’s demo?</h2><p>This removes locally created articles and source edits and restores the prepared examples. Export any work you want to keep first.</p><div class="row"><button class="btn" data-action="close-modal">Cancel</button><button class="btn primary" data-action="reset">Reset demo</button></div>');}
 if(action==='reset'){state=seed();persist();closeModal();location.hash='#/overview';render();notify('Demo workspace restored.');}
});
document.addEventListener('input',ev=>{if(ev.target.id==='article-search')filterLibrary();if(ev.target.id==='source-search'){const q=ev.target.value.toLowerCase();document.querySelector('#knowledge-grid').innerHTML=state.sources.filter(s=>(s.title+' '+s.kind+' '+s.text).toLowerCase().includes(q)).map(sourceCard).join('')||'<div class="empty">No matching sources.</div>';}});
document.addEventListener('change',ev=>{if(['status-filter','type-filter'].includes(ev.target.id))filterLibrary();if(ev.target.id==='brief-approval')document.querySelector('#generate-btn').disabled=!ev.target.checked;});
window.addEventListener('hashchange',()=>{if(!busy){tab='overview';render();window.scrollTo(0,0);}});
if(!location.hash)location.hash='#/overview';render();
